name: firmware

# For now, this workflow is used for checks, not for releases.
# So all release stuff is commented out.

on:
  push:
    # branches:
    #   - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request: {}

permissions:
  contents: write

jobs:
  doom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # or 'true' for non-recursive
          fetch-depth: 0         # fetch full history, required for submodules to work properly
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ./.pio
          key: ${{ runner.os }}-doom
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./
        run: pio run -e v2

      - name: Copy firmware
        working-directory: ./
        run: |
          cp .pio/build/v2/firmware.bin doom.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: doom-firmware
          path: ./doom.bin
